#!/usr/bin/env bash
# Idempotent repository bootstrap for the Ki Distributers Cloud Agent environment.
# Installs the PHP/MySQL toolchain, prepares the local dev database, and writes a
# local includes/config.php. Safe to run repeatedly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DB_NAME="kd_dev"
DB_USER="kd_dev"
DB_PASS="kd_dev_pass"

echo "==> Ensuring PHP + MariaDB are installed"
if ! command -v php >/dev/null 2>&1 || ! command -v mariadb >/dev/null 2>&1; then
    sudo apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
        php-cli php-mysql php-mbstring mariadb-server mariadb-client
fi
php -v | head -1

echo "==> Starting MariaDB (needed to create the dev database)"
if ! sudo mariadb -e "SELECT 1" >/dev/null 2>&1; then
    sudo service mariadb start || sudo mariadbd-safe --datadir=/var/lib/mysql >/tmp/mariadb-install.log 2>&1 &
    for _ in $(seq 1 30); do
        sudo mariadb -e "SELECT 1" >/dev/null 2>&1 && break
        sleep 1
    done
fi

echo "==> Creating database and application user (idempotent)"
sudo mariadb <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

echo "==> Importing schema if the database is empty"
TABLE_COUNT="$(mariadb -N -u "${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" \
    -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}'" 2>/dev/null || echo 0)"
if [ "${TABLE_COUNT}" -eq 0 ]; then
    mariadb -u "${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" < sql/schema.sql
    mariadb -u "${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" < sql/seeds.sql
    echo "    schema + seeds imported"
else
    echo "    ${TABLE_COUNT} tables already present, skipping import"
fi

echo "==> Writing includes/config.php (gitignored) if missing"
if [ ! -f includes/config.php ]; then
    cat > includes/config.php <<'PHP'
<?php
// Local development config (gitignored). Generated by .cursor/install.sh.
return [
    'db' => [
        'host'     => '127.0.0.1',
        'name'     => 'kd_dev',
        'user'     => 'kd_dev',
        'password' => 'kd_dev_pass',
        'charset'  => 'utf8mb4',
    ],
    'app' => [
        'name'          => 'Ki Distributers',
        'short_name'    => 'KD',
        'session_name'  => 'KI_SESSION',
        'max_pin_tries' => 5,
        'lock_seconds'  => 30,
        'timezone'      => 'Asia/Kolkata',
    ],
    'hub' => [
        'name' => 'Ki',
        'businesses' => [
            [
                'id'       => 'kd',
                'name'     => 'Ki Distributers',
                'subtitle' => 'Outlets · orders · van · stock',
                'href'     => '/index.php',
                'icon'     => 'distribution',
            ],
        ],
    ],
];
PHP
    echo "    wrote includes/config.php"
else
    echo "    includes/config.php already exists, leaving it"
fi

echo "==> Install complete"
